apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
  namespace: kube-system
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "static-ingress"
  KUBEIP_SELF_NODEPOOL: "silvester-nodepool-apps"
  KUBEIP_NODEPOOL: "silvester-nodepool-ingress"
  KUBEIP_FORCEASSIGNMENT: "true"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"