apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ .Chart.Name }}-iam-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: [{{ .Values.gsaServiceAccount }}]
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:[{{ .Values.projectId }}].svc.id.goog[[{{ .Release.Namespace }}]/[{{ .Chart.Name }}-serviceaccount]]