name: Provision GCP Anthos Cluster
on:
  push:
    branches:
      - refs/tags/*
      
jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: silvester-304916
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: "Setup Terraform CLI"
      uses: hashicorp/setup-terraform@v1.0.1
 
    - name: "Run Terraform Init"
      run: terraform init -input=false
 
    - name: "Run Terraform Apply"
      run: terraform apply -input=false -auto-approve