name: Terraform Apply

on:
  push:
    branches:        
      - "master"

jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: silvester-304916
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: "Setup Terraform CLI"
      uses: hashicorp/setup-terraform@v1
 
    - name: "CLUSTER - Terraform Init"
      run: terraform -chdir=cluster init -input=false

    - name: "CLUSTER - Import cluster"
      run: terraform -chdir=cluster import google_container_cluster.silvester_cluster europe-west1-b/silvester-cluster 
      continue-on-error: true

    - name: "CLUSTER - Import ingress node pool"
      run: terraform -chdir=cluster import google_container_node_pool.silvester_nodepool_ingress europe-west1-b/silvester-cluster/silvester-nodepool-ingress 
      continue-on-error: true

    - name: "CLUSTER - Import apps node pool"
      run: terraform -chdir=cluster import google_container_node_pool.silvester_nodepool_apps europe-west1-b/silvester-cluster/silvester-nodepool-apps 
      continue-on-error: true

    - name: "CLUSTER - Terraform Apply"
      run: terraform -chdir=cluster apply -input=false -auto-approve



    - name: "KUBERNETES - Terraform Init"
      run: terraform -chdir=kubernetes init -input=false

    - name: "KUBERNETES - Set Credentials"
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: silvester-cluster
        location: europe-west1-b
        credentials: ${{ secrets.GCP_SA_KEY }}

    - run: export TF_VAR_kubeconfig_path=$KUBECONFIG

    - name: "KUBERNETES - Terraform Apply"
      run: terraform -chdir=kubernetes  "kubeconfig_path=$KUBECONFIG" apply -input=false -auto-approve