name: Terraform Apply

on:
  push:
    branches:        
      - "master"

jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v1



    - name: INSTALL - Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: silvester-304916
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: "INSTALL - Terraform CLI"
      uses: hashicorp/setup-terraform@v1
 
    - name: INSTALL - Helm CLI
      uses: azure/setup-helm@v1




    - name: "CLUSTER - Terraform - Init"
      run: terraform init -input=false

    - name: "CLUSTER - Terraform - Import - Cluster"
      run: terraform import google_container_cluster.silvester_cluster europe-west1-b/silvester-cluster 
      continue-on-error: true

    - name: "CLUSTER - Terraform - Import - Ingress Node Pool"
      run: terraform import google_container_node_pool.silvester_nodepool_ingress europe-west1-b/silvester-cluster/silvester-nodepool-ingress 
      continue-on-error: true

    - name: "CLUSTER - Terraform - Import - Apps Node Pool"
      run: terraform import google_container_node_pool.silvester_nodepool_apps europe-west1-b/silvester-cluster/silvester-nodepool-apps 
      continue-on-error: true

    - name: "CLUSTER - Terraform - Apply"
      run: terraform apply -input=false -auto-approve



    - name: "KUBERNETES - Install Nginx Ingress Controller"
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install ingress-nginx/ingress-nginx -f ./charts/nginx-ingress-controller/values.yaml --namespace ingress-nginx