name: Terraform Apply

on:
  push:
    branches:        
      - "master"

jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: silvester-304916
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: "Setup Terraform CLI"
      uses: hashicorp/setup-terraform@v1
 
    - name: "Init terraform"
      run: terraform init -input=false
 
    - name: "Import container cluster"
      run: terraform import google_container_cluster.silvester_cluster europe-west1-b/silvester-cluster
      continue-on-error: true

    - name: "Import ingress node pool"
      run: terraform import google_container_node_pool.silvester_nodepool_ingress europe-west1-b/silvester-cluster/silvester-nodepool-ingress
      continue-on-error: true

    - name: "Import node pool"
      run: terraform import google_container_node_pool.silvester_nodepool_apps europe-west1-b/silvester-cluster/silvester-nodepool-apps
      continue-on-error: true
      
    - name: "Import nginx namespace"
      run: terraform import kubernetes_namespace.ingress_nginx europe-west1-b/silvester-cluster/ingress-nginx
      continue-on-error: true

    - name: "Import nginx serviceaccount"
      run: terraform import kubernetes_service_account.ingress_nginx_service_account europe-west1-b/ingress_nginx_service_account
      continue-on-error: true

    - name: "Run Terraform Apply"
      run: terraform apply -input=false -auto-approve