name: Terraform Apply

on:
  push:
    branches:        
      - "master"

jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: silvester-304916
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: "Setup Terraform CLI"
      uses: hashicorp/setup-terraform@v1
 
    - name: "Init terraform - Cluster"
      run: terraform -chdir=cluster init -input=false

    - name: "Init terraform - Kubernetes"
      run: terraform -chdir=kubernetes init -input=false
 
    - name: "Import container cluster"
      run: terraform -chdir=cluster import google_container_cluster.silvester_cluster europe-west1-b/silvester-cluster 
      continue-on-error: true

    - name: "Import ingress node pool"
      run: terraform -chdir=cluster import google_container_node_pool.silvester_nodepool_ingress europe-west1-b/silvester-cluster/silvester-nodepool-ingress 
      continue-on-error: true

    - name: "Import apps node pool"
      run: terraform -chdir=cluster import google_container_node_pool.silvester_nodepool_apps europe-west1-b/silvester-cluster/silvester-nodepool-apps 
      continue-on-error: true

    - name: "Run Terraform Apply - Cluster"
      run: terraform -chdir=cluster apply -input=false -auto-approve

    - id: get-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: my-cluster
        location: europe-west1-b
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: "Run Terraform Apply - Kubernetes"
      run: terraform -chdir=kubernetes apply -input=false -auto-approve